1. Single Dimensional
   1. Access single elements (indexing)
   2. Access multiple elements (slicing)
2. Multi-Dimensional
   1. Access rows 
   2. Access columns

Single Dimensional Array

In [14]:
import numpy as np

In [15]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
# access first element
a[0]

np.int64(1)

In [17]:
a[1]

np.int64(2)

In [18]:
# last element
a[-1]

np.int64(20)

In [19]:
a[-2]

np.int64(19)

Slicing

In [20]:
# a[first_index:last_index]

In [21]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
a[1:10]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
a[0:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
a[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
a[5:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Multidimensional

In [29]:
b = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]
])

In [30]:
b[0]

array([1, 2, 3])

In [31]:
b[1]

array([4, 5, 6])

In [33]:
b[:,0]

array([1, 4, 7])

In [34]:
b[:, 1]

array([2, 5, 8])

In [ ]:
# b[start_row:end_row , start_col:end_col]