In [1]:
import numpy as np

In [2]:
x = np.arange(1, 11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
x[0]

np.int64(1)

In [4]:
x[1]

np.int64(2)

In [5]:
x[0:4]

array([1, 2, 3, 4])

In [6]:
x[2:7]

array([3, 4, 5, 6, 7])

Syntax for multidimensional numpy array

```python
x[row_ind, col_ind]

x[ row_start_ind:row_end_ind , col_start_ind:col_end_ind]
```

In [7]:
# Convert row matrix to column matrix

x.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])